$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  reference:
    type: object
    properties:
      dct:
        type: string
      fasta:
        type: string
      intervals:
        type: string
      loci:
        type: string
    required:
      - dct
      - fasta
      - intervals
      - loci
  mutect2:
      type: object
      properties:
        gnomad:
          type: string
      required:
        - gnomad
  tools:
    type: object
    properties:
      cnvkit:
        type: string
      gatk:
        type: string
  required:
    - samples
    - units
    - reference
    - tools
